export const books = [
  { title: "Capital in the Twenty-First Century", author: "Piketty" },
  { title: "Steve Jobs", author: "Isaacson" },
  { title: "The Anxious Generation", author: "Haidt" },
  { title: "Poverty by America", author: "Desmond" },
  { title: "A Moveable Feast", author: "Hemingway" },
  { title: "These Truths", author: "Lepore" },
  { title: "Almanack of Naval Ravikant", author: "Jorgenson" },
  { title: "Inferno", author: "Hastings" },
  { title: "Shoe Dog", author: "Knight" },
  { title: "The Psychology of Money", author: "Housel" },
  { title: "Antifragile", author: "Taleb" },
  { title: "Zero to One", author: "Thiel" },
  { title: "Poor Charlie's Almanack", author: "Kaufman" },
  { title: "Learning From Data", author: "Magdon-Ismail" },
  { title: "Fast Food Nation", author: "Schlosser" },
  { title: "Why Nations Fail", author: "Acemoglu" },
  { title: "How Fascism Works", author: "Stanley" },
];
